### ISSUE TITLE
Information on which protocols are being used? (e.g. references to scientific papers)

### ISSUE THREAD

**Issue by matthiasgeihs** [cicada-mpc/cicada-mpc#79]
Hey, this looks like a nice project!

I've been wondering: Is there an easy way to find out which protocols are being implemented?
E.g. which paper is followed for active security?
Which bit decomposition protocol is used?

Would be nice to include references to the respective scientific papers in the documentation and/or the code.

**Comment by tshead2** [comment]
Thanks for your interest!  When we remember, we include paper references in our API reference documentation - for example, the active security paper is described in the documentation for [ActiveProtocolSuite](https://cicada-mpc.readthedocs.io/en/stable/cicada.active.html#cicada.active.ActiveProtocolSuite).  I'll go find the bit decomposition reference; in the meantime, don't hesitate to ask for what you need!

Cheers,
Tim

**Comment by matthiasgeihs** [comment]
Thanks for the pointer!

**Comment by matthiasgeihs** [comment]
Had some time to look into this and searched for the work referenced in the ActiveProtocolSuite. I realized then that this points to a PhD thesis which does not seem to be available to the public. Is the protocol described somewhere else? Did it undergo peer-review?

**Comment by kgoss1729** [comment]
Regarding the protocol for active security, it did receive review by the board of advisors on the committee referenced in the document. The protocol was not published in an academic conference or journal since before it could be published another was published which had a slightly better asymptotic complexity and interest in the protocol in the thesis was no longer sufficient. It does include complexity analysis and a security proof which you can study and judge for yourself. We have considered adding other protocols for active security but have not had the bandwidth yet to be able to do so. 

On the source of the protocol for bit decomposition, it is a straightforward application of the least-significant-bit extraction protocol by Nishide and Ohta (https://iacr.org/archive/pkc2007/44500343/44500343.pdf) in an iterative manner to extract all the bits. This is not the most efficient means by which this operation can be done, but since we were using the least significant bit extraction elsewhere, bit decomposition in this manner came largely for "free" in terms of development time. Adding a more efficient bit decomposition protocol is possible but would likely require heavy use of this primitive to motivate given development time constraints at present.

**Comment by matthiasgeihs** [comment]
I understand. Maybe it would still be worthwhile publishing on eprint (or similar) for easier access?

**Comment by kgoss1729** [comment]
I did not realize that it was very difficult to access. That sounds reasonable to me. Thanks for the suggestion.

**Comment by kgoss1729** [comment]
The access of the dissertation/thesis has been opened up. It was restricted as a part of some error. Here is a [link](https://mospace.umsystem.edu/xmlui/handle/10355/84279) where it is hosted at the original university. I have not yet got it on Arxiv and the cryptology eprint archive doesn't accept dissertations or the like. I am closing this issue for now as it seems resolved to me.

**Comment by matthiasgeihs** [comment]
Great, that helps!

**Comment by kgoss1729** [comment]
It is now also on Arxiv: https://arxiv.org/abs/2311.08934

That one is actually slightly updated with some typos and the like fixed.

**Comment by kgoss1729** [comment]
It wound up making it into the thesis which is now on both the originating university and Arxiv at the provided link in chapter 2. It just never made it into a conference or journal outside the thesis. I agree with you in principle that alternative protocols may be of interest even though their complexity may not be optimal, however asymptotic complexity reigns supreme it would seem to me for the purposes of publishing in many of these venues.
